[package]
name = "spice-rs-sdk-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spiceai = "2.0.0"
tokio = "1.37.0"
