name: gardener

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "19 18 * * 4"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: gardener

jobs:
  edge-test:
    name: test gardener on trunk build
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17

    steps:
      - uses: actions/checkout@v2
        with:
          repository: spiceai/spiceai
          path: ./spiceai

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}

      - name: Build and copy dashboard
        working-directory: dashboard
        run: make

  released-test:
    name: test gardener on latest released binaries
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update PATH
        run: |
          echo "PATH=~/.spice/bin:$PATH" >> $GITHUB_ENV

      - name: install Spice.ai
        run: |
          curl https://install.spiceai.org | /bin/bash

      - name: start Spice.ai runtime
        run: |
          spice run &

      - name: wait for Spice.ai runtime healthy
        run: |
          timeout 120 bash -c 'while [[ "$(curl -s -w 200 http://localhost:8000/health)" != "ok200" ]]; do sleep 1; done' || false

      - name: fetch diagnostics
        run: |
          curl http://localhost:8000/api/v0.1/diagnostics

      - name: get sample pod
        run: |
          spice add samples/gardener

      - name: fetch pods
        run: |
          curl -s http://localhost:8000/api/v0.1/pods | jq

      - name: fetch observations
        run: |
          curl http://localhost:8000/api/v0.1/pods/gardener/observations

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: start gardener sample app
        run: |
          timeout 180 python main.py | tee gardener.out || true

      - name: fetch recommendations
        run: |
          curl -s http://localhost:8000/api/v0.1/pods/gardener/recommendation | grep -E "confidence" && echo "Fetched recommendation from trained model" || exit 1

      - name: check output for success
        run: |
          grep -E "Watering" gardener.out && echo "Found successful action based on recommendation" || exit 1
