name: gardener

on:
  push:
    branches:
      - trunk
    paths:
      - "gardener/**"
  pull_request:
    branches:
      - trunk
    paths:
      - "gardener/**"
  schedule:
    - cron: "19 18 * * 4"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: gardener

jobs:
  gardener:
    name: gardener> ${{ matrix.display_name }}
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17

    strategy:
      fail-fast: false
      matrix:
        version: [released, edge]
        include:
          - version: released
            context: docker
            spicepod_version: latest
            display_name: https://install.spiceai.org
          - version: edge
            context: metal
            spicepod_version: latest
            display_name: spiceai/spiceai@trunk

    steps:
      - uses: actions/checkout@v2

      - name: install Spice.ai (edge, metal)
        if: matrix.version == 'edge'
        uses: ./.github/actions/install-edge-metal

      - name: update PATH
        if: matrix.version == 'released'
        run: |
          echo "PATH=~/.spice/bin:$PATH" >> $GITHUB_ENV

      - name: install Spice.ai (https://install.spiceai.org)
        if: matrix.version == 'released'
        run: |
          curl https://install.spiceai.org | /bin/bash

      - name: start Spice.ai runtime (context ${{ matrix.context }})
        run: |
          spice run --context ${{ matrix.context }} &

      - name: wait for Spice.ai runtime healthy
        run: |
          timeout 120 bash -c 'while [[ "$(curl -s -w 200 http://localhost:8000/health)" != "ok200" ]]; do sleep 1; done' || false

      - name: fetch diagnostics
        run: |
          curl http://localhost:8000/api/v0.1/diagnostics

      - name: spice add samples/gardener@${{ matrix.spicepod_version }}
        if: matrix.spicepod_version != 'latest'
        run: |
          spice add samples/gardener@${{ matrix.spicepod_version }}

      - name: spice add samples/gardener
        if: matrix.spicepod_version == 'latest'
        run: |
          spice add samples/gardener

      - name: fetch pods
        run: |
          curl -s http://localhost:8000/api/v0.1/pods | jq

      - name: fetch observations
        run: |
          curl http://localhost:8000/api/v0.1/pods/gardener/observations

      - name: fetch recommendations
        run: |
          curl -s http://localhost:8000/api/v0.1/pods/gardener/recommendation

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: start gardener sample app
        run: |
          timeout 180 python main.py | tee gardener.out || true

      - name: fetch recommendations
        run: |
          curl -s http://localhost:8000/api/v0.1/pods/gardener/recommendation
          curl -s http://localhost:8000/api/v0.1/pods/gardener/recommendation | grep -E "confidence" && echo "Fetched recommendation from trained model" || exit 1

      - name: check output for success
        run: |
          cat gardener.out
          grep -E "Watering" gardener.out && echo "Found successful action based on recommendation" || exit 1
