name: serverops

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "19 18 * * 4"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: serverops

jobs:
  serverops:
    name: serverops> ${{ matrix.display_name }}
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17

    strategy:
      fail-fast: false
      matrix:
        version: [released, edge]
        include:
          - version: released
            context: docker
            spicepod_version: latest
            display_name: https://install.spiceai.org
          - version: edge
            context: metal
            spicepod_version: 0.2.0
            display_name: spiceai/spiceai@trunk

    steps:
      - uses: actions/checkout@v2

      - name: bring up influxdb/telegraf
        run: docker-compose up -d

      - name: install Spice.ai (edge, metal)
        if: matrix.version == 'edge'
        uses: ./.github/actions/install-edge-metal

      - name: update PATH
        if: matrix.version == 'released'
        run: |
          echo "PATH=~/.spice/bin:$PATH" >> $GITHUB_ENV

      - name: install Spice.ai (https://install.spiceai.org)
        if: matrix.version == 'released'
        run: |
          curl https://install.spiceai.org | /bin/bash

      - name: wait for influxdb start and metrics collection
        run: |
          sleep 30
          curl -s http://localhost:8086

      - name: start Spice.ai runtime (context ${{ matrix.context }})
        run: |
          source set-spice-vars.sh
          spice run --context ${{ matrix.context }} &

      - name: wait for Spice.ai runtime healthy
        run: |
          timeout 60 bash -c 'while [[ "$(curl -s -w 200 http://localhost:8000/health)" != "ok200" ]]; do sleep 1; done' || false

      - name: fetch diagnostics
        run: |
          curl -s http://localhost:8000/api/v0.1/diagnostics

      - name: spice add samples/serverops@${{ matrix.spicepod_version }}
        if: matrix.spicepod_version != 'latest'
        run: |
          spice add samples/serverops@${{ matrix.spicepod_version }}

      - name: spice add samples/serverops
        if: matrix.spicepod_version == 'latest'
        run: |
          spice add samples/serverops

      - name: fetch pods
        run: |
          curl -s http://localhost:8000/api/v0.1/pods | jq

      - name: fetch observations
        run: |
          curl -s http://localhost:8000/api/v0.1/pods/serverops/observations

      - name: fetch recommendation
        run: |
          curl -s http://localhost:8000/api/v0.1/pods/serverops/recommendation | jq

      - name: start serverops sample app
        run: |
          timeout 60 pwsh serverops.ps1 | tee serverops.out || true

      - name: fetch recommendations
        run: |
          curl -s http://localhost:8000/api/v0.1/pods/serverops/recommendation | jq
          curl -s http://localhost:8000/api/v0.1/pods/serverops/recommendation | grep -E "confidence" && echo "Fetched recommendation from trained model" || exit 1

      - name: check output for success
        run: |
          grep -E "any|now" serverops.out && echo "Found successful action based on recommendation" || exit 1
